INSERT INTO Room (RoomName) VALUES ('B1-01');
INSERT INTO Room (RoomName) VALUES ('B1-02');
INSERT INTO Room (RoomName) VALUES ('B1-03');
INSERT INTO Room (RoomName) VALUES ('B1-04');
INSERT INTO Room (RoomName) VALUES ('B1-05');
INSERT INTO Room (RoomName) VALUES ('B1-06');
INSERT INTO Room (RoomName) VALUES ('B1-07');
INSERT INTO Room (RoomName) VALUES ('B1-08');
INSERT INTO Room (RoomName) VALUES ('B1-09');
INSERT INTO Room (RoomName) VALUES ('B1-10');
INSERT INTO Room (RoomName) VALUES ('B1-11');
INSERT INTO Room (RoomName) VALUES ('B1-12');

INSERT INTO Device VALUES (NULL,'MKRFOX_schathe','1');
INSERT INTO Device VALUES (NULL,'MKRFOX_almecin','2');
INSERT INTO Device VALUES (NULL,'MKRFOX_bouerob','12');

INSERT INTO Measure VALUES (NULL,'12','1e','24562456',1);
INSERT INTO Measure VALUES (NULL,'20','24','265245',2);
INSERT INTO Measure VALUES (NULL,'1a','19','756342',3);
